### ISSUE TITLE
초 기능 문의

### ISSUE THREAD

**Issue by rapune** [nhnent/tui.time-picker#2]
안녕하세요, 초 기능 관련하여 문의 드립니다.

현재 api랑 wiki를 찾아봤지만...
현재 버전에서 "시:분"만 지원하고 "초"단위는 지원하지 않는 것이 맞는지요?

"초"단위를 지원하지 않는것이 현재 내부 정책이라면,
추후 지원할 계획은 있는지요?

**Comment by seonim-ryu** [comment]
@rapune 
안녕하세요. 먼저 TUI 컴포넌트를 사용해주셔서 감사합니다.
현재 '초' 단위 기능은 지원하지 않고 있으나 추후 기능 개선 때 추가할 수 있을 것으로 보입니다.
해당 기능에 대해서 직접 개발하셔서 풀리퀘스트를 날려주셔도 좋습니다.
그럼 확인 부탁드립니다. :)
