### ISSUE TITLE
Using Change Event

### ISSUE THREAD

**Issue by Jo-Pitts** [nhnent/tui.time-picker#51]
## Version
Latest

## Development Environment
Windows, Chrome

## Current Behavior
I am very novice and can't work out how to attach event code to the change event.  There is nothing in the documentation.  Can you please document and/or provide worked example.

**Comment by swtalk** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
박시우(viewrain@nhn.com) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
박시우(viewrain@nhn.com) 
          
          
            * 발송 시간 : 
2021-01-04T11:33:16
          
          
            * 메일 제목 : 
[nhn/tui.time-picker] Using Change Event (#51)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          dooray@nhn.com
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by lja1018** [comment]
@Jo-Pitts 
I fixed the missing example for the change event.
You can check it [here](https://nhn.github.io/tui.time-picker/latest/TimePicker#event-change).
Thank you!

**Comment by swtalk** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
박시우(viewrain@nhn.com) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
박시우(viewrain@nhn.com) 
          
          
            * 발송 시간 : 
2021-01-05T16:14:16
          
          
            * 메일 제목 : 
Re: [nhn/tui.time-picker] Using Change Event (#51)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          dooray@nhn.com
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by Jo-Pitts** [comment]
Perect!  Thanks
