### ISSUE TITLE
There is issue while using timepicker using range and step

### ISSUE THREAD

**Issue by shyamsamtan** [nhnent/tui.time-picker#65]
const TimePicker = tui.TimePicker;
            timepicker1 = new TimePicker('#timepicker-spinbox1', {
                inputType: 'selectbox',
                showMeridiem: true,
                minuteStep: 15,
            });

var begin = { hour: 6, minute: 15 };
var end = { hour: 11, minute: 15 };
timepicker1.setRange(begin, end);

while selecting time from beginning, all the minutes are disabled

**Comment by shyamsamtan** [comment]
timepicker1.getHour() also does not show the current hour

**Comment by jajugoguma** [comment]
@shyamsamtan 
Thank you for raising the issue.
It seems to be a problem caused by not considering the step in the code that disable the minute.
I'll fix it ASAP.
