### ISSUE TITLE
How to get the selected meridiem?

### ISSUE THREAD

**Issue by habibieamrullah** [nhnent/tui.time-picker#68]
Hello, I tried to use "change" listener, but...
When I console.log(e.hour, e.minute), I tried to also have e.meridiem but it's not possible. How could I get the meridiem value?

**Comment by jajugoguma** [comment]
There is currently no way to get meridiem directly.
Another way is to get the current hour and check the quotient of dividing it by 12.
```js
const timePicker = new TimePicker( /* */, {
  //...
});

const isPM = timePicker.getHour() / 12 >= 1;
```

**Comment by habibieamrullah** [comment]
Yeah nevermind, I simply think to use 24 h time format instead.
